apiVersion: v1
kind: Service
metadata:
  name: {{include "bulletinapp.fullname" .}}
  labels: {{- include "bulletinapp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{ default "80" .Values.service.port}}
      targetPort: {{ default "80" .Values.service.targetPort }}
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "80" .Values.service.nodePort }}
      {{ end }}
      name: http
  selector: {{- include "bulletinapp.selectorLabels" . | nindent 4}}
